import mongoose, { Schema } from 'mongoose'

const StartupSchema = new Schema(
  {
    id: { type: String, index: true, unique: true },
    userId: { type: String, index: true },
    ideaText: String,
    targetCustomer: String,
    problem: String,
    scorecardJson: Schema.Types.Mixed,
    warPlanJson: Schema.Types.Mixed,
    devilsAdvocateJson: Schema.Types.Mixed,
    failureProbability: Number,
    survivalEdge: String,
    founderDNA: Schema.Types.Mixed,
    completedTasks: [{ taskId: String, completedAt: Date }],
    taskEdits: [{ taskId: String, original: String, edited: String, vznComment: String, editedAt: Date }],
    tractionDetails: [{ type: String, value: String, loggedAt: Date }],
    introRequests: [{ vcName: String, requestedAt: Date }],
    shareCardsGenerated: { type: Number, default: 0 },
    pivotAlerts: [{ triggeredAt: Date, signals: [String], message: String, dismissedAt: Date }],
    subscriptionTier: { type: String, default: 'free' },
    accountabilityScore: { type: Number, default: 0 },
    taskCompletionRate: { type: Number, default: 0 },
    vaultUnlocked: { type: Boolean, default: false },
    oath: String,
    oathDate: Date,
    stressTestResponse: String,
    tractionProof: { type: Boolean, default: false },
    burnRate: Number,
    cashInBank: Number,
    monthlyRevenue: Number,
    vznVoice: String,
    // Market Intelligence
    marketIntelligence: {
      ideaOriginality: { score: Number, verdict: String, explanation: String },
      directCompetitors: [{ name: String, status: String, foundedYear: String, funding: String, whyTheyMatter: String, theirWeakness: String, shutdownReason: String }],
      indirectCompetitors: [{ name: String, overlap: String, threat: String }],
      marketStatus: { stage: String, timing: String, timingExplanation: String, indianMarketSpecific: String },
      graveyardWarning: { hasDeadStartups: Boolean, count: Number, mostRelevantDeathStory: String, patternAcrossDeaths: String },
      whitespace: { exists: Boolean, description: String, why: String },
      vcSentiment: { currentInterest: String, explanation: String, recentFundingSignals: String },
      vznVerdict: String,
      biggestThreat: String,
      unfairAdvantage: String,
      generatedAt: Date,
    },
    competitorAwarenessAnswers: [String],
    trackedCompetitors: [String],
    competitorNotes: [{ competitorName: String, week: Number, notes: String, date: Date }],
    dayDebriefs: [{
      week: Number,
      day: Number,
      prepAnswers: [String],
      prepFeedback: String,
      executionCount: Number,
      executionNotes: [String],
      subStepsCompleted: [String],
      timeSpentMinutes: Number,
      debrief: { whatHappened: String, theSignal: String, whatItMeans: String, whatChanges: String, tomorrowEdge: String },
      vznResponse: String,
      patternFlag: String,
      urgencyLevel: String,
      competitiveInsight: String,
      tomorrowSuggestion: String,
      completedAt: Date,
      dayCardShared: Boolean,
    }],
    weekAnalyses: [{
      week: Number,
      patterns: [String],
      warnings: [String],
      strengths: [String],
      weekScore: Number,
      nextWeekFocus: String,
      vznVerdict: String,
      generatedAt: Date,
    }],
    decisionFollowUps: [{
      decisionId: Schema.Types.ObjectId,
      dueDate: Date,
      completedAt: Date,
      actualOutcome: String,
      vznAccuracy: String,
      vznAutopsy: String,
    }],
    weekUnlockStatus: [{
      week: Number,
      unlocked: Boolean,
      unlockedAt: Date,
    }],
  },
  { timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' } },
)

export default mongoose.models.Startup || mongoose.model('Startup', StartupSchema)
