'use client'

import { FormEvent, useState, useEffect } from 'react'
import { useSession } from 'next-auth/react'
import AppShell from '@/components/AppShell'
import VZNAvatar from '@/components/ui/VZNAvatar'
import VznMatrixCore from '@/components/dashboard/VznMatrixCore'
import { addNotification } from '@/lib/client-notifications'
import { Sparkles, Calendar, TrendingUp, AlertTriangle, CheckSquare, Award, Clock } from 'lucide-react'

const types = ['pricing', 'hiring', 'pivot', 'fundraising', 'product', 'go-to-market']

const loadingSteps = [
  { title: 'RUNNING MONTE CARLO SCENARIO ANALYSIS...', desc: 'VZN is evaluating GTM, pricing, and resource allocation vectors...' },
  { title: 'MAPPING PRODUCT AND MARKET VELOCITY VECTORS...', desc: 'Simulating competitor response curves and market saturation...' },
  { title: 'CALCULATING CO-FOUNDER DILUTION AND RISK VALUE...', desc: 'Analyzing founder alignment, speed of execution, and lock-in models...' },
  { title: 'ESTIMATING 30/90/180 DAY OUTCOME PROBABILITIES...', desc: 'Calculating probability curves for best, worst, and most likely cases...' },
  { title: 'DRAFTING FINAL VERDICT AND REASONING...', desc: 'Synthesizing simulation inputs into a brutal VZN co-founder recommendation...' }
]

export default function DecisionsPage() {
  const { data: session } = useSession()
  const [description, setDescription] = useState('')
  const [decisionType, setDecisionType] = useState(types[0])
  const [loading, setLoading] = useState(false)
  const [loadingStep, setLoadingStep] = useState(0)
  const [result, setResult] = useState<any>(null)
  const [error, setError] = useState('')
  const user = session?.user as any

  // Decisions list & Autopsy states
  const [startupId, setStartupId] = useState('guest')
  const [savedDecisions, setSavedDecisions] = useState<any[]>([])
  const [selectedDecisionId, setSelectedDecisionId] = useState<string | null>(null)
  const [actualOutcome, setActualOutcome] = useState('')
  const [autopsyLoading, setAutopsyLoading] = useState(false)
  const [autopsyError, setAutopsyError] = useState('')

  useEffect(() => {
    if (!loading) {
      setLoadingStep(0)
      return
    }
    const interval = setInterval(() => {
      setLoadingStep((prev) => (prev < loadingSteps.length - 1 ? prev + 1 : prev))
    }, 3200)
    return () => clearInterval(interval)
  }, [loading])

  // Load startup decisions from localStorage & handle URL query id param
  useEffect(() => {
    if (typeof window === 'undefined') return
    const activeId = window.localStorage.getItem('visionix_active_startup_id') || 'guest'
    setStartupId(activeId)

    const stored = window.localStorage.getItem(`veixon_decisions_${activeId}`)
    let list: any[] = []
    if (stored) {
      try {
        list = JSON.parse(stored)
        setSavedDecisions(list)
      } catch (e) {
        console.error(e)
      }
    }

    // Check query params
    const urlParams = new URLSearchParams(window.location.search)
    const idParam = urlParams.get('id')
    if (idParam) {
      const found = list.find((d: any) => d.id === idParam)
      if (found) {
        loadDecision(found)
      }
    }
  }, [])

  function loadDecision(d: any) {
    setSelectedDecisionId(d.id)
    setDescription(d.description)
    setDecisionType(d.decisionType)
    setActualOutcome(d.actualOutcome || '')
    setResult({
      recommendation: d.recommendation,
      reasoning: d.reasoning,
      bestCase: d.bestCase,
      mostLikely: d.mostLikely,
      worstCase: d.worstCase,
      vzn_voice: d.vzn_voice || d.vznVoice || 'Recommendation generated by VZN co-founder simulator.',
      vznAccuracy: d.vznAccuracy,
      vznAutopsy: d.vznAutopsy
    })
  }

  function startNewSimulation() {
    setSelectedDecisionId(null)
    setDescription('')
    setDecisionType(types[0])
    setResult(null)
    setActualOutcome('')
    setError('')
    setAutopsyError('')
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!description.trim()) {
      setError('A decision description is required. VZN cannot simulate an empty thought. Please type what you are considering.')
      return
    }
    setLoading(true)
    setError('')
    try {
      const response = await fetch('/api/ai/decision', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          description,
          decisionType,
          startupId: window.localStorage.getItem('visionix_active_startup_id') || 'guest',
          userId: user?.id || user?.email || 'anonymous',
          email: user?.email,
          name: user?.name,
        }),
      })
      const data = await response.json()
      if (!response.ok || data.error) {
        throw new Error(data.error || 'Failed to simulate decision')
      }
      
      setResult(data)
      
      // Save locally
      const activeId = window.localStorage.getItem('visionix_active_startup_id') || 'guest'
      const newDecision = {
        id: data.id || Math.random().toString(36).substring(2, 9),
        description,
        decisionType,
        recommendation: data.recommendation,
        reasoning: data.reasoning,
        bestCase: data.bestCase,
        mostLikely: data.mostLikely,
        worstCase: data.worstCase,
        vzn_voice: data.vzn_voice || data.vznVoice || 'Recommendation generated by VZN co-founder simulator.',
        createdAt: new Date().toISOString()
      }
      
      const stored = window.localStorage.getItem(`veixon_decisions_${activeId}`)
      const currentList = stored ? JSON.parse(stored) : []
      const updatedList = [newDecision, ...currentList]
      window.localStorage.setItem(`veixon_decisions_${activeId}`, JSON.stringify(updatedList))
      setSavedDecisions(updatedList)
      setSelectedDecisionId(newDecision.id)
      
      addNotification(`AI Simulated decision on ${decisionType || 'general'}: "${description.substring(0, 30)}..."`, "/decisions")
    } catch (err: any) {
      console.error(err)
      setError(err.message || 'VZN simulation failed. Try again.')
    } finally {
      setLoading(false)
    }
  }

  // Autopsy submission handler
  async function submitAutopsy() {
    if (!actualOutcome.trim() || !selectedDecisionId) return
    setAutopsyLoading(true)
    setAutopsyError('')

    try {
      const response = await fetch('/api/ai/decision-autopsy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          decisionText: description,
          actualOutcome: actualOutcome
        })
      })
      const data = await response.json()
      if (!response.ok || data.error) {
        throw new Error(data.error || 'Failed to analyze autopsy')
      }

      // Update in result state
      setResult((prev: any) => ({
        ...prev,
        vznAccuracy: data.vznAccuracy,
        vznAutopsy: data.vznAutopsy
      }))

      // Persist in local storage list
      const activeId = window.localStorage.getItem('visionix_active_startup_id') || 'guest'
      const updatedList = savedDecisions.map((d) => {
        if (d.id === selectedDecisionId) {
          return {
            ...d,
            actualOutcome,
            vznAccuracy: data.vznAccuracy,
            vznAutopsy: data.vznAutopsy
          }
        }
        return d
      })
      window.localStorage.setItem(`veixon_decisions_${activeId}`, JSON.stringify(updatedList))
      setSavedDecisions(updatedList)

      addNotification(`Decision Autopsy completed for: "${description.substring(0, 25)}..."`, `/decisions?id=${selectedDecisionId}`)
    } catch (err: any) {
      console.error(err)
      setAutopsyError(err.message || 'Autopsy process failed. Please try again.')
    } finally {
      setAutopsyLoading(false)
    }
  }

  return (
    <AppShell title="Decision Simulator" subtitle="Best case. Worst case. Most likely. Then the call.">
      <div className="mx-auto grid w-full max-w-7xl gap-6 p-4 md:grid-cols-[380px_1fr] md:p-8">
        
        {/* LEFT COLUMN: SIMULATE FORM & SAVED LIST */}
        <div className="space-y-6">
          <form onSubmit={submit} className="vzn-panel-strong rounded-[1.5rem] p-6 border" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
            <div className="flex justify-between items-center mb-4">
              <VZNAvatar size="md" />
              {selectedDecisionId && (
                <button
                  type="button"
                  onClick={startNewSimulation}
                  className="text-xs text-[var(--purple)] hover:underline flex items-center gap-1 font-mono uppercase"
                >
                  <Clock className="h-3 w-3" /> New Sim
                </button>
              )}
            </div>
            
            <h2 className="text-xl font-bold">What decision are you avoiding?</h2>
            <textarea
              value={description}
              onChange={(event) => {
                setDescription(event.target.value)
                if (error) setError('')
              }}
              rows={5}
              placeholder="Should we pivot from SMBs to enterprise buyers?"
              className="focus-ring vzn-input mt-4 resize-none rounded-xl p-4 text-xs"
              style={error && error.includes('required') ? { borderColor: 'var(--amber)', boxShadow: '0 0 0 1px var(--amber)' } : undefined}
            />
            
            <div className="mt-4 grid grid-cols-2 gap-2">
              {types.map((type) => (
                <button
                  type="button"
                  key={type}
                  onClick={() => setDecisionType(type)}
                  className="vzn-button-ghost veixon-press rounded-lg border px-3 py-1.5 text-xs capitalize transition-colors"
                  style={{
                    borderColor: decisionType === type ? 'var(--purple)' : 'var(--border)',
                    color: decisionType === type ? 'var(--purple)' : 'var(--text-muted)',
                  }}
                >
                  {type}
                </button>
              ))}
            </div>
            
            <button 
              disabled={loading} 
              className="vzn-button-primary mt-5 w-full rounded-xl px-5 py-3 text-xs font-semibold disabled:opacity-60"
            >
              {loading ? 'VZN is simulating...' : 'Simulate decision'}
            </button>
          </form>

          {/* HISTORICAL DECISIONS LIST */}
          <div className="vzn-panel rounded-[1.5rem] p-6 border text-left" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
            <span className="text-[10px] font-mono uppercase tracking-widest text-[var(--purple)] font-bold block mb-4">
              Simulated Decisions History
            </span>
            {savedDecisions.length === 0 ? (
              <p className="text-xs text-[var(--text-dim)] font-mono italic">No simulated decisions saved yet.</p>
            ) : (
              <div className="space-y-3 max-h-[300px] overflow-y-auto pr-1">
                {savedDecisions.map((d) => (
                  <button
                    key={d.id}
                    onClick={() => loadDecision(d)}
                    className="w-full text-left p-3 rounded-xl border text-xs transition-all hover:bg-white/2 block"
                    style={{
                      borderColor: selectedDecisionId === d.id ? 'var(--purple)' : 'var(--border)',
                      background: selectedDecisionId === d.id ? 'rgba(168,85,247,0.03)' : 'transparent'
                    }}
                  >
                    <div className="flex justify-between items-center mb-1 text-[9px] font-mono text-[var(--text-dim)]">
                      <span className="capitalize text-[var(--purple)] font-bold">{d.decisionType}</span>
                      <span>{new Date(d.createdAt || Date.now()).toLocaleDateString()}</span>
                    </div>
                    <p className="truncate text-white font-medium">{d.description}</p>
                    {d.vznAccuracy && (
                      <span className="inline-block mt-1 text-[8px] uppercase font-bold tracking-widest text-teal-400 bg-teal-500/10 px-1.5 py-0.5 rounded">
                        Autopsy: {d.vznAccuracy}
                      </span>
                    )}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* RIGHT COLUMN: SIMULATOR RESULTS & 30-DAY AUTOPSY */}
        <section className="vzn-panel rounded-[1.5rem] p-6 border" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
          {loading ? (
            <div className="grid h-full min-h-[420px] place-items-center text-center">
              <div>
                <div className="scale-125 mb-4">
                  <VznMatrixCore />
                </div>
                <p className="mt-4 text-sm text-[var(--purple)] font-mono tracking-widest animate-pulse">
                  {loadingSteps[loadingStep].title}
                </p>
                <p className="text-xs text-[var(--text-muted)] mt-1.5">
                  {loadingSteps[loadingStep].desc}
                </p>
              </div>
            </div>
          ) : error ? (
            <div className="grid h-full min-h-[420px] place-items-center text-center">
              <div>
                <VZNAvatar size="lg" mood="warning" className="mx-auto mb-5" />
                <p className="font-bold text-lg" style={{ color: error.includes('required') ? 'var(--amber)' : 'var(--red)' }}>
                  {error.includes('required') ? 'Decision Required' : 'Simulation Failed'}
                </p>
                <p className="text-sm mt-1.5" style={{ color: 'var(--text-muted)' }}>{error}</p>
              </div>
            </div>
          ) : !result ? (
            <div className="grid h-full min-h-[420px] place-items-center text-center" style={{ color: 'var(--text-dim)' }}>
              <div className="max-w-sm">
                <VZNAvatar size="lg" className="mx-auto mb-5" />
                <p className="text-sm font-semibold">Simulate potential choices to compute Best, Worst, and Most-Likely scenarios instantly.</p>
                <p className="text-xs mt-2">The verdict will not be gentle.</p>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div>
                <div className="text-xs font-semibold uppercase tracking-widest text-[var(--purple)]">Recommendation</div>
                <h2 className="mt-2 text-2xl font-bold">{result.recommendation}</h2>
                <p className="mt-3 text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>{result.reasoning}</p>
              </div>

              <div className="grid gap-4 lg:grid-cols-3">
                {[
                  ['Best Case', result.bestCase],
                  ['Most Likely', result.mostLikely],
                  ['Worst Case', result.worstCase],
                ].map(([label, scenario]: any, idx: number) => (
                  <div key={label} className="vzn-panel veixon-lift veixon-rise rounded-xl p-4 border text-xs" style={{ ['--d' as any]: `${idx * 0.07}s`, borderColor: 'rgba(255,255,255,0.03)' }}>
                    <h3 className="font-bold text-white text-sm mb-2">{label}</h3>
                    <p className="text-xs leading-relaxed mb-3 text-white/90">{scenario?.summary}</p>
                    <div className="space-y-1.5 border-t pt-2 font-mono text-[10px]" style={{ color: 'var(--text-muted)' }}>
                      <p><strong>Day 30:</strong> {scenario?.day30}</p>
                      <p><strong>Day 90:</strong> {scenario?.day90}</p>
                      <p><strong>Day 180:</strong> {scenario?.day180}</p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="rounded-xl border p-4 text-[var(--amber)] text-xs font-semibold" style={{ borderColor: 'rgba(245, 158, 11, 0.3)', background: 'rgba(245, 158, 11, 0.03)' }}>
                VZN Voice: {result.vzn_voice}
              </div>

              {/* 30-DAY AUTOPSY MODULE */}
              {selectedDecisionId && (
                <div className="border-t pt-6" style={{ borderColor: 'rgba(255,255,255,0.06)' }}>
                  <div className="flex items-center gap-2 mb-3">
                    <Award className="h-5 w-5 text-[var(--purple)]" />
                    <span className="text-xs font-bold text-white uppercase tracking-wider">30-Day Decision Autopsy</span>
                  </div>

                  {/* If autopsy not logged yet */}
                  {!result.vznAutopsy ? (
                    <div className="bg-white/2 rounded-2xl p-5 border space-y-4" style={{ borderColor: 'rgba(255,255,255,0.04)' }}>
                      <p className="text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>
                        Compare VZN's predictive scenarios to reality. Tell VZN what actually happened to lock down lessons.
                      </p>
                      <textarea
                        value={actualOutcome}
                        onChange={(e) => setActualOutcome(e.target.value)}
                        rows={3}
                        placeholder="E.g., We deployed this, but customer acquisition took twice as long and ARR growth stalled..."
                        className="vzn-input w-full rounded-xl p-3 text-xs resize-none"
                      />
                      
                      {autopsyError && <p className="text-xs text-red-400 font-mono">{autopsyError}</p>}

                      <button
                        onClick={submitAutopsy}
                        disabled={autopsyLoading || !actualOutcome.trim()}
                        className="vzn-button-primary rounded-xl px-4 py-2 text-xs font-semibold disabled:opacity-50"
                      >
                        {autopsyLoading ? 'Analyzing reality gap...' : 'Perform VZN Autopsy'}
                      </button>
                    </div>
                  ) : (
                    /* If autopsy completed, render analysis */
                    <div className="space-y-4">
                      <div className="vzn-panel-strong rounded-2xl p-5 border" style={{ borderColor: 'rgba(20, 184, 166, 0.2)' }}>
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-[10px] font-mono uppercase tracking-widest text-[var(--purple)] font-bold">Reality Log</span>
                          <span className="rounded-full px-2 py-0.5 text-[9px] font-bold font-mono uppercase bg-teal-500/10 text-teal-400 border border-teal-500/25">
                            Accuracy: {result.vznAccuracy}
                          </span>
                        </div>
                        <p className="text-xs text-white/90 font-mono leading-relaxed italic">"{actualOutcome}"</p>
                      </div>

                      <div className="bg-white/2 rounded-2xl p-5 border shadow-inner" style={{ borderColor: 'rgba(255,255,255,0.04)' }}>
                        <span className="text-[10px] font-mono uppercase tracking-widest block text-[var(--amber)] font-bold mb-2">
                          VZN Autopsy Critique
                        </span>
                        <p className="text-xs leading-relaxed text-white/95 font-medium border-l-2 pl-3" style={{ borderColor: 'var(--amber)' }}>
                          {result.vznAutopsy}
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </section>
      </div>
    </AppShell>
  )
}
